### ISSUE TITLE
Сверстать страницу Welcome

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/membership_accounting#3]
### Критерии приемки
- [x] Сверстать страницу в соответсвии с этим макетом
![image](https://user-images.githubusercontent.com/14871471/154058827-71a03fb9-b5fa-475c-bb90-f8686220917a.png)

**Comment by Tim-Shelll** [comment]
#9

**Comment by YuriSilenok** [comment]
> #9

Не понял, зачем это?
